#! /bin/bash
#
# ~/.bashrc-avail.d/git-puller - git pull local repositories from remote
#

set -u

BASEDIR=~/Workspace

ACTION=${1:-fetch}
#ACTION=${1:-pull}

for R in $BASEDIR/*/; do
	logger -t git -p info "git pull $R"
#	printf "+---\n"
#	printf "+ repo %s:\n" "$(basename $R)"
	printf "+--- %+59s repository ---+\n" "$(basename $R)"
	pushd $R >> /dev/null
	git status
	git remote -v
	for R in $(git remote -v | awk '{print $1}' | sort | uniq); do
		git $ACTION -v $R
	done
	popd >> /dev/null
done

#.
