#! /bin/bash
#
# ~/.bashrc-avail.d/git-puller - git pull local repositories from remote
#

BASEDIR=~/Workspace

ACTION=${1:-fetch}
#ACTION=${1:-pull}

for R in $BASEDIR/*/; do
	logger -t git -p info "git pull $R"
	printf "+ repo %s:\n" "$(basename $R)"
	pushd $R >> /dev/null
	git remote -v
	git $ACTION
	popd >> /dev/null
done

#.
