#! /bin/bash
#
# ~/.bashrc-avail.d/git-puller - git pull local repositories from remote
#

BASEDIR=~/Workspace

for R in $BASEDIR/*/; do
	logger -t git -p info "git pull $R"
	printf "+ repo %s: " "$(basename $R)"
	pushd $R >> /dev/null
	#git pull
	git fetch
	popd >> /dev/null
done

#.
